# Generated by Django 4.0.3 on 2024-03-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SePayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('account_number', models.CharField(max_length=20)),
                ('sub_account', models.CharField(max_length=20)),
                ('amount_in', models.FloatField()),
                ('amount_out', models.FloatField()),
                ('accumulated', models.FloatField()),
                ('transaction_content', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=50)),
                ('bank_brand_name', models.CharField(max_length=50)),
                ('bank_account_id', models.CharField(max_length=50)),
            ],
        ),
    ]
