# Generated by Django 4.0.3 on 2024-03-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepaytransaction',
            name='accumulated',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sepaytransaction',
            name='amount_in',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sepaytransaction',
            name='amount_out',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
