# Generated by Django 5.0.2 on 2024-03-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepay', '0003_remove_sepaytransaction_bank_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepaytransaction',
            name='sub_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
