# Generated by Django 5.0.2 on 2024-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepay', '0004_alter_sepaytransaction_sub_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepaytransaction',
            name='transaction_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
