# Generated by Django 5.0.2 on 2024-03-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0004_maintransaction_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=100)),
                ('signature', models.CharField(default='', max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('lamports', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('confirmation_status', models.CharField(default='', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.maintransaction')),
            ],
        ),
    ]
