# Generated by Django 5.0.2 on 2024-03-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaptransaction',
            name='network',
        ),
    ]
