# Generated by Django 5.0.2 on 2024-03-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_remove_swaptransaction_network'),
        ('transaction', '0006_maintransaction_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaptransaction',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.maintransaction'),
        ),
    ]
