# Generated by Django 5.0.2 on 2024-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='created', max_length=10)),
                ('bank_brand_name', models.CharField(choices=[('OCB', 'ocb')], default='ocb', max_length=10)),
                ('sub_account', models.CharField(max_length=20)),
                ('amount_in', models.FloatField()),
                ('in_currency_unit_id', models.CharField(choices=[('VND', 'vnd'), ('SOL', 'sol')], default='vnd', max_length=20)),
                ('wallet_address', models.CharField(max_length=100)),
                ('amount_out', models.FloatField()),
                ('out_currency_unit_id', models.CharField(choices=[('VND', 'vnd'), ('SOL', 'sol')], default='sol', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
