# Generated by Django 5.0.2 on 2024-03-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_brand_name',
            field=models.CharField(choices=[('ocb', 'OCB')], default='ocb', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='in_currency_unit_id',
            field=models.CharField(choices=[('vnd', 'VND'), ('sol', 'SOL')], default='vnd', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='out_currency_unit_id',
            field=models.CharField(choices=[('vnd', 'VND'), ('sol', 'SOL')], default='sol', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='created', max_length=10),
        ),
    ]
