# Generated by Django 5.0.2 on 2024-03-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('WAITING_BANK_TRANSFER', 'Waiting bank transfer'), ('COMPLETE_BANK_TRANSFER', 'Completed bank transfer'), ('CREATE_CRYPTO_TRANSER', 'Created crypto transaction'), ('COMPLETE_CRYPTO_TRANSFER', 'Completed crypto transaction'), ('COMPLETED', 'Completed'), ('CREAFAILEDTED', 'Failed')], default='CREATED', max_length=30)),
                ('bank_brand_name', models.CharField(choices=[('OCB', 'OCB')], default='ocb', max_length=10)),
                ('sub_account', models.CharField(max_length=20)),
                ('amount_in', models.FloatField()),
                ('in_currency_unit_id', models.CharField(choices=[('vnd', 'VND'), ('sol', 'SOL')], default='vnd', max_length=20)),
                ('receiver_wallet_address', models.CharField(max_length=100)),
                ('amount_out', models.FloatField()),
                ('out_currency_unit_id', models.CharField(choices=[('vnd', 'VND'), ('sol', 'SOL')], default='sol', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
