# Generated by Django 5.0.2 on 2024-03-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_maintransaction_delete_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintransaction',
            old_name='sub_account',
            new_name='account_number',
        ),
    ]
