# Generated by Django 5.0.2 on 2024-03-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_sub_account_maintransaction_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintransaction',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
