# Generated by Django 5.0.2 on 2024-03-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_maintransaction_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintransaction',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
